[project]
name = "freetokenoreore"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "freetoken",
    "freetoken-kernel-cache",
    "torch>=2.11,<2.12",
    "tornado>=6.1",
]

[dependency-groups]
dev = [
    "ninja>=1.13.2",
]

[tool.uv]
link-mode = "copy"
environments = [
    "sys_platform == 'win32' and platform_machine == 'AMD64'",
]
required-environments = [
    "sys_platform == 'win32' and platform_machine == 'AMD64'",
]

[tool.uv.sources]
torch = { index = "pytorch-cu130" }
freetoken = { url = "https://github.com/FlashML-org/FreeToken-Web/releases/download/beta/freetoken-0.1.2%2Bg141c31a8d-cp312-cp312-win_amd64.whl" }
freetoken-kernel-cache = { url = "https://github.com/FlashML-org/FreeToken-Web/releases/download/beta/freetoken_kernel_cache-0.1.2%2Bcu130.g141c31a8d-py3-none-win_amd64.whl" }

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true
